title: Hossein Nassiri, Solution Architect
description: Feel free to bookmark this to keep an eye on my projects!

show_downloads: ["false"]
google_analytics: [Your Google Analytics tracking ID]

remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
