title: Hossein Nassiri, Solution Architect
description: Feel free to bookmark this to keep an eye on my projects!
email: hossein.nassiri@gmail.com
github_username: hosseinnassiri

show_downloads: false
# Your Google Analytics tracking ID
google_analytics:

remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
    collection_nav_links:
      output: true
    collection_projects:
      output: true
    collection_social:
      output: true

content:
  -_projects:
    - title: "My Projects"
      description: "A collection of my projects and their details."
      url: "/projects/"
      image: "/assets/images/projects.jpg"
    - title: "My Blog"
      description: "A collection of my blog posts and articles."
      url: "/blog/"
      image: "/assets/images/blog.jpg"
